/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Remove session from cookies
 */
export type DeleteApiLogout204 = any

export type DeleteApiLogoutMutationResponse = DeleteApiLogout204

export type DeleteApiLogoutMutation = {
  Response: DeleteApiLogout204
  Errors: any
}