/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Remove session from cookies
 */
export type DeleteApiAuthLogout204 = any

export type DeleteApiAuthLogoutMutationResponse = DeleteApiAuthLogout204

export type DeleteApiAuthLogoutMutation = {
  Response: DeleteApiAuthLogout204
  Errors: any
}