/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiAuthSignInGoogle200 = any;

export type GetApiAuthSignInGoogleQueryResponse = GetApiAuthSignInGoogle200;

export type GetApiAuthSignInGoogleQuery = {
  Response: GetApiAuthSignInGoogle200;
  Errors: any;
};
