/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Redirect to google auth screen (then back to \'/\', possibly with obtained session)
 */
export type GetApiAuthSignInGoogle302 = any

export type GetApiAuthSignInGoogleQueryResponse = any

export type GetApiAuthSignInGoogleQuery = {
  Response: any
  Errors: any
}