/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiAuthLogout200 = any;

export type GetApiAuthLogoutQueryResponse = GetApiAuthLogout200;

export type GetApiAuthLogoutQuery = {
  Response: GetApiAuthLogout200;
  Errors: any;
};
