/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description If present - return Session, associated with user, otherwise - empty object
 */
export type GetApiAuthWhoami200 = any

export type GetApiAuthWhoamiQueryResponse = GetApiAuthWhoami200

export type GetApiAuthWhoamiQuery = {
  Response: GetApiAuthWhoami200
  Errors: any
}