/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiAuthWhoami200 = {
  iam?: any;
};

export type GetApiAuthWhoamiQueryResponse = GetApiAuthWhoami200;

export type GetApiAuthWhoamiQuery = {
  Response: GetApiAuthWhoami200;
  Errors: any;
};
