/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiLogout200 = any

export type GetApiLogoutQueryResponse = GetApiLogout200

export type GetApiLogoutQuery = {
  Response: GetApiLogout200
  Errors: any
}