/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Parse swagger json to yaml format
 */
export type GetApiSwaggerYaml200 = any;

export type GetApiSwaggerYamlQueryResponse = GetApiSwaggerYaml200;

export type GetApiSwaggerYamlQuery = {
  Response: GetApiSwaggerYaml200;
  Errors: any;
};
