/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Remove session from cookies
 */
export type GetApiAuthLogout204 = any

export type GetApiAuthLogoutQueryResponse = GetApiAuthLogout204

export type GetApiAuthLogoutQuery = {
  Response: GetApiAuthLogout204
  Errors: any
}