/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Redirect user back to application.
 */
export type GetApiAuthGoogleCallback302 = any

export type GetApiAuthGoogleCallbackQueryResponse = any

export type GetApiAuthGoogleCallbackQuery = {
  Response: any
  Errors: any
}