/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiAuthGoogleCallback200 = any;

export type GetApiAuthGoogleCallbackQueryResponse = GetApiAuthGoogleCallback200;

export type GetApiAuthGoogleCallbackQuery = {
  Response: GetApiAuthGoogleCallback200;
  Errors: any;
};
