/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetApiAuthWhoami200 = {
  /**
   * @type object | undefined
   */
  iam?: {
    /**
     * @type string
     */
    _tag: string;
    /**
     * @type string
     */
    _id: string;
    /**
     * @type string
     */
    email: string;
  };
};

export type GetApiAuthWhoamiQueryResponse = GetApiAuthWhoami200;

export type GetApiAuthWhoamiQuery = {
  Response: GetApiAuthWhoami200;
  Errors: any;
};
