openapi: 3.0.3
info:
  title: hft API
  description: Development documentation
  version: 0.1.1
externalDocs:
  url: /
  description: UI
paths:
  /api/auth/whoami:
    get:
      responses:
        "200":
          description: >-
            If present - return Session, associated with user, otherwise - empty
            object
      operationId: getApiAuthWhoami
  /api/auth/sign-in/google:
    get:
      operationId: getApiAuthSign-inGoogle
      responses:
        "302":
          description: >-
            Redirect to google auth screen (then back to '/', possibly with
            obtained session)
  /api/auth/logout:
    get:
      responses:
        "204":
          description: Remove session from cookies
      operationId: getApiAuthLogout
components:
  schemas: {}
